version: "3.8"
services:
  ui:
    image: nginx:alpine
    volumes:
      - ./admin:/usr/share/nginx/html/admin
      - ./schemas:/usr/share/nginx/html/schemas
      - ./admin/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    restart: unless-stopped

  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install && node server.js"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=sahar-cohen1/example_schema_registry
      - GITHUB_BRANCH=master
    ports:
      - "8081:3000"
    restart: unless-stopped 