# admin/config.yml
backend:
  name: github
  repo: sahar-cohen1/example_schema_registry
  branch: master
  base_url: https://growing-optical-rhode-comm.trycloudflare.com
  auth_endpoint: /admin/auth
  api_root: /admin/api/v1

media_folder: "schemas"
public_folder: "/schemas"

collections:
  - name: schemas
    label: Schemas
    folder: schemas
    create: true
    extension: json
    format: json
    fields:
      - {label: "Schema Name", name: "schema_name", widget: "string"}
      - {label: "Version", name: "version", widget: "number", default: 1}
      - {label: "Type", name: "schema_type", widget: "string"}
      - {label: "Approved", name: "approved", widget: "boolean", default: false}
      - {label: "Created At", name: "created_at", widget: "datetime"}
      - {label: "Updated At", name: "updated_at", widget: "datetime"}
      - {label: "Schema Definition", name: "schema", widget: "code", default_language: "json"}